// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
	"go-mq/application/consumer"
	"go-mq/application/service"
	"go-mq/application/service/facade"
	"go-mq/infrastructure/queue"
	"go-mq/infrastructure/svc"
)

// Injectors from wire.go:

// InitializeUserFacade 初始化统计门面服务
func InitializeUserFacade(svcCtx *svc.ServiceContext) *facade.UserFacade {
	healthRepository := ProviderHealthRepo(svcCtx)
	queueManager := ProviderQueueManager(svcCtx)
	healthService := ProviderHealthService(healthRepository, queueManager)
	statisticsRepository := ProviderStatisticsRepo(svcCtx)
	statisticsService := ProviderStatisticsService(statisticsRepository)
	userFacade := ProviderUserFacade(healthService, statisticsService)
	return userFacade
}

// InitializeHealthService 初始化健康服务
func InitializeHealthService(svcCtx *svc.ServiceContext) *service.HealthService {
	healthRepository := ProviderHealthRepo(svcCtx)
	queueManager := ProviderQueueManager(svcCtx)
	healthService := ProviderHealthService(healthRepository, queueManager)
	return healthService
}

// InitializeStatisticsService 初始化统计服务
func InitializeStatisticsService(svcCtx *svc.ServiceContext) *service.StatisticsService {
	statisticsRepository := ProviderStatisticsRepo(svcCtx)
	statisticsService := ProviderStatisticsService(statisticsRepository)
	return statisticsService
}

// InitializeHealthConsumer 初始化健康消费者
func InitializeHealthConsumer(svcCtx *svc.ServiceContext) *consumer.HealthConsumer {
	queueManager := ProviderQueueManager(svcCtx)
	healthRepository := ProviderHealthRepo(svcCtx)
	healthService := ProviderHealthService(healthRepository, queueManager)
	statisticsRepository := ProviderStatisticsRepo(svcCtx)
	statisticsService := ProviderStatisticsService(statisticsRepository)
	userFacade := ProviderUserFacade(healthService, statisticsService)
	healthConsumer := ProviderHealthConsumer(queueManager, userFacade)
	return healthConsumer
}

// InitializeConsumerManager 初始化消费者管理器
func InitializeConsumerManager(svcCtx *svc.ServiceContext) *queue.ConsumerManager {
	queueManager := ProviderQueueManager(svcCtx)
	consumerManager := ProviderConsumerManager(queueManager)
	return consumerManager
}

// wire.go:

// userProviderSet 定义用户服务相关的依赖提供者
var providerSet = wire.NewSet(

	RepositoryProviderSet,

	ServiceProviderSet,

	FacedeServiceProviderSet,
)
